    repos:
      - repo: https://github.com/ambv/black
        rev: 24.10.0
        hooks:
          - id: black
            language_version: python.3.12.2
      -   repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v2.0.0
          hooks:
          - id: flake8