# Generated by Django 5.0.2 on 2024-05-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home_page_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=1000)),
                ("price", models.CharField(max_length=300)),
                ("adress", models.CharField(max_length=1000)),
                ("postal_code", models.CharField(max_length=100)),
            ],
        ),
    ]
