# Generated by Django 5.0.2 on 2024-05-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Main_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=1000)),
                ("price", models.CharField(max_length=300)),
                ("adress", models.CharField(max_length=400)),
                ("image", models.ImageField(upload_to="main_products")),
                ("discount", models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name="home_page_products",
            name="discount",
            field=models.CharField(default="", max_length=400),
            preserve_default=False,
        ),
    ]
