# Generated by Django 5.0.2 on 2024-05-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_main_products_home_page_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_products',
            name='image',
            field=models.ImageField(default='', upload_to='home_products'),
            preserve_default=False,
        ),
    ]
