# Generated by Django 5.0.2 on 2024-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_home_page_products_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_products",
            name="postal_code",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
