# Generated by Django 5.0.2 on 2024-05-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_main_products_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_products",
            name="platform",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
