# Generated by Django 5.0.2 on 2024-05-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_main_products_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='paid_plan')),
            ],
        ),
    ]
