# Generated by Django 5.0.2 on 2024-05-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.ImageField(upload_to="challan_requesta")),
            ],
        ),
    ]
