# Generated by Django 5.0.2 on 2024-05-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_challan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challan",
            old_name="upload",
            new_name="send",
        ),
    ]
