# Generated by Django 5.0.2 on 2024-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_sign_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='id',
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
