# Generated by Django 5.0.2 on 2024-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
