# Generated by Django 5.0.2 on 2024-05-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_challan_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challan",
            name="email",
        ),
    ]
