# Generated by Django 5.0.2 on 2024-05-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_remove_temporary_email_temporary_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="challan",
            name="email",
            field=models.EmailField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
