# Generated by Django 5.0.6 on 2024-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_challan_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
