# Generated by Django 5.0.2 on 2024-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_home_page_products_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporary',
            name='id',
        ),
        migrations.AlterField(
            model_name='temporary',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
