# Generated by Django 5.0.2 on 2024-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_order_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(upload_to="shop_requests"),
        ),
    ]
