# Generated by Django 5.0.2 on 2024-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=40)),
                ('cnic', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='shop_requests')),
            ],
        ),
    ]
