# Generated by Django 5.0.2 on 2024-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_remove_approved_shops_id_remove_shop_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shops_data",
            fields=[
                (
                    "shop_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("shop_name", models.CharField(max_length=100)),
            ],
        ),
    ]
