# Generated by Django 5.0.2 on 2024-05-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_alter_shop_products_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="shops_data",
            name="email",
            field=models.CharField(
                default=1, max_length=100, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shops_data",
            name="shop_id",
            field=models.CharField(max_length=100),
        ),
    ]
