# Generated by Django 5.0.2 on 2024-05-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_shop_products_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_products',
            old_name='discout',
            new_name='discount',
        ),
    ]
